config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root "static_pages#top"
  get 'login', to: "user_sessions#new"
  post 'login', to: "user_sessions#create"
  post 'guest_login', to: "user_sessions#guest_login"
  delete 'logout', to: "user_sessions#destroy"
  resources :users, only: %i[new create]
  resources :posts do
    get 'bookmarks', on: :collection
    resources :comments, only: %i[create destroy], shallow: true
  end
  resources :bookmarks, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :body, presence: true, length: { maximum: 65_535 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, through: :bookmarks, source: :post

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true

  def own?(object)
    id == object.user_id
  end

  def bookmark(post)
    bookmark_posts << post
  end

  def unbookmark(post)
    bookmark_posts.destroy(post)
  end

  def bookmark?(post)
    bookmark_posts.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger, :warning
  before_action :require_login

  private
  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to login_path
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    current_user.bookmark(@post)
  end

  def destroy
    @post = current_user.bookmarks.find(params[:id]).post
    current_user.unbookmark(@post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[edit update destroy] 

  def index
    @posts = Post.all.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.all.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: (t 'defaults.message.created', item: Post.model_name.human)
    else
      flash.now[:danger] = (t 'defaults.message.not_created', item: Post.model_name.human)
      render :new
    end
  end

  def edit ;end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), success: (t 'defaults.message.updated', item: Post.model_name.human)
    else
      flash.now[:danger] = t 'defaults.message.not_updated', item: Post.model_name.human
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, success: (t 'defaults.message.deleted', item: Post.model_name.human )
  end

  def bookmarks
    @bookmark_posts = current_user.bookmark_posts.includes(:user).order(created_at: :desc).page(params[:page]).per(10)
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end

  def find_post
    @post = current_user.posts.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  
  def top ;end 
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create guest_login]
  
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to posts_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def guest_login
    @guest_user = User.create(
      name: "ゲスト",
      email: SecureRandom.alphanumeric(20) + "@email.com",
      password: "password",
      password_confirmation: "password"
    )
    auto_login(@guest_user)
    redirect_to new_post_path, success: "ゲストログインしました"
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = 'Vague Memories'
    
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end  
end

app/views/bookmarks/create.js.erb
$("#js-bookmark-button-for-post-<%= @post.id %>").replaceWith("<%= j(render('posts/unbookmark', post: @post)) %>")

app/views/bookmarks/destroy.js.erb
$("#js-bookmark-button-for-post-<%= @post.id %>").replaceWith("<%= j(render('posts/bookmark', post: @post)) %>")

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td>
    <h3 class="small"><%= comment.user.name %></h3>
    <div id="js-comment-<%= comment.id %>">
      <p><%= simple_format(comment.body) %></p>
    </div>
    <div id="js-textarea-comment-box-<%= comment.id %>" style="display: none;">
      <textarea id="js-textarea-comment-<%= comment.id %>" class="form-control mb-1"><%= comment.body %></textarea>
      <button class="btn btn-light">キャンセル</button>
      <button class="btn btn-success">更新</button>
    </div>
  </td>
  <% if current_user.own?(comment) %> 
    <td class="action">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to comment_path(comment), class: 'js-delete-comment-button', method: :delete, data: { confirm: t('defaults.message.delete_confirm')}, remote: true do %>
            <%= icon 'fa', 'trash' %> 
          <% end %> 
        </li>
      </ul>
    </td>
  <% end %> 
</tr>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <table id="js-table-comment" class="table">
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-6 offset-lg-3">
    <%= form_with model: comment, url: [post, comment], id: 'new_comment' do |f| %>
      <%= f.label :body %>
      <%= f.text_area :body, class: "form-control mb-3", id: 'js-new-comment-body', row:"4", placeholder: Comment.human_attribute_name(:body) %>
      <%= f.hidden_field :post_id %>
      <%= f.submit t('defaults.post'), class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$("#error_messages").remove()

<% if @comment.errors.present? %>
  $("#new_comment").prepend("<%= j(render('shared/error_messages', object: @comment)) %>")
<% else %>
  $("#js-table-comment").prepend("<%= j(render('comments/comment', comment: @comment)) %>")
  $("#js-new-comment-body").val('')
<% end %>

app/views/comments/destroy.js.erb
$("tr#comment-<%= @comment.id %>").remove()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/posts/_bookmark.html.erb
<%= link_to bookmarks_path(post_id: post.id), id: "js-bookmark-button-for-post-#{post.id}", class: "float-right", method: :post, remote: true  do %>
  <%= icon 'far', 'star'%>
<% end %>

app/views/posts/_bookmark_button.html.erb
<% if current_user.bookmark?(post) %>
  <%= render 'unbookmark', post: post %>
<% else%>
  <%= render 'bookmark', post: post %>
<% end %>

app/views/posts/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <%= link_to edit_post_path(post), id: "button-edit-#{post.id}" do %>
      <%= icon 'fa', 'pen' %>
    <% end %>
  </li>
  <li class="list-inline-item">
    <%= link_to post_path(post), id: "button-delete-#{post.id}", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
      <%= icon 'fas', 'trash' %>
    <% end %>
  </li>
</ul>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control", rows: "5" %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= link_to post.body, post_path(post), class: 'text-body fuzzy-text', data:{ random_index: "0" } %>
  </td>
  <td>
    <%= post.user.name %>
  </td>
  <td>
    <%= l post.created_at, format: :long %>
  </td>
  <td>  
    <% if current_user.own?(post) %>
      <%= render 'crud_menus', post: post %>
    <% else %>
      <%= render 'bookmark_button', post: post %>
    <% end %>
  </td>
</tr>

app/views/posts/_unbookmark.html.erb
<%= link_to bookmark_path(current_user.bookmarks.find_by(post_id: post.id)), id: "js-bookmark-button-for-post-#{post.id}",class: "float-right", method: :delete, remote: true  do %>
  <%= icon 'fas', 'star'%>
<% end %>

app/views/posts/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12"> 
      <div class="row d-flex justify-content-end mb-3">
        <div class="col-md-2">
          <%= link_to "一覧へ", posts_path, class: "btn btn-success" %>
        </div>
        <div class="col-md-3">
          <%= button_tag "思い出フィルターを外す", class: "btn btn-danger", onclick: "window.location.reload();" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col", style="width: 60%"><%= Post.human_attribute_name(:body) %></th>
          <th scope="col", style="width: 15%"><%= Post.human_attribute_name(:user) %></th>
          <th scope="col", style="width: 10%"><%= Post.human_attribute_name(:created_at) %></th>
          <th scope="col", style="width: 15%"></th>
        </thead>
        <tbody>
        <% if @bookmark_posts.present? %>
          <%= render @bookmark_posts %>
        <% else%>
          <%= t '.no_result'%>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <!-- ページネーション -->
      <%= paginate @bookmark_posts %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12"> 
      <div class="row d-flex justify-content-end mb-3">
        <div class="col-md-3">
          <%= button_tag "思い出フィルターを外す", class: "btn btn-danger", onclick: "window.location.reload();" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col", style="width: 60%"><%= Post.human_attribute_name(:body) %></th>
          <th scope="col", style="width: 15%"><%= Post.human_attribute_name(:user) %></th>
          <th scope="col", style="width: 10%"><%= Post.human_attribute_name(:created_at) %></th>
          <th scope="col", style="width: 15%"></th>
        </tr>
        </thead>
        <tbody>
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <%= t '.no_result' %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <!-- ページネーション -->
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-6 offset-lg-3">
      <h1><%= t('.title') %></h1>
      <div class="row">
        <div class="col-md-12"> 
          <div class="row d-flex justify-content-end mb-3">
            <div class="col-md-3">
              <%= link_to "一覧へ", posts_path, class: "btn btn-success" %>
            </div>
            <div class="col-md-5">
              <%= button_tag "思い出フィルターを外す", class: "btn btn-danger", onclick: "window.location.reload();" %>
            </div>
          </div>
        </div>
      </div>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-12'>
              <h5><%= simple_format(@post.body, class: 'fuzzy-text') %></h5>
              <%= render 'crud_menus', post: @post if current_user.own?(@post) %>
              <ul class="list-inline">
                <li class="list-inline-item"><%= "posted by #{@post.user.name}" %></li>
                <li class="list-inline-item"><%= l @post.created_at, format: :long %></li>
                <li class="list-inline-item float-right">
                  <%= link_to "https://twitter.com/share?url=#{ request.url }&text= #{@post.body}", target: '_blank' do %>
                    <i class="fab fa-twitter" style='color: #3399FF;'></i>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </article>
    </div>
  </div>

  <%= render 'comments/form', {post: @post, comment: @comment} %>

  <%= render 'comments/comments', {comments: @comments} %>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%#= image_tag '#' %>
    <% end %>
    
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to "ログイン", login_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_flash_message_html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p> </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <a class='navbar-brand' href='/'>
      <%#= image_tag "#" %>
    </a>
    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ml-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
            <%= "思い出" %>
          </a>

          <div class='dropdown-menu dropdown-menu-right'>
            <%= link_to "思い出一覧", posts_path, class: 'dropdown-item' %>
            <%= link_to "思い出作成", new_post_path,  class: 'dropdown-item' %>
          </div>
        </li>

        <li class='nav-item'>
          <%= link_to "ブックマーク一覧", bookmarks_posts_path,  class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <a href='#' class='nav-link' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='header-profile'>
            <%= image_tag "sample.jpg", size: '40x40', class: 'rounded-circle mr15' %>
          </a>
          <div class='dropdown-menu dropdown-menu-right'>
            <div class='dropdown-item'><%= current_user.name %></div>
            <div class='dropdown-divider'></div>
            <%= link_to "プロフィール", "#", class: 'dropdown-item' %>
            <%= link_to "ログアウト", logout_path, class: 'dropdown-item', method: :delete %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/top.html.erb
<div class='top-wrapper'>
  <div class='top-inner-text'>
    <h1>Vague Memories</h1>
    <p>トップページです。コレから更新します。</p>
    <%= link_to "さっそく思い出を投稿する", guest_login_path, method: :post, class: "btn btn-success" %>
    <%= link_to "新規登録", new_user_path, class: "btn btn-primary" %>
    <%= link_to "ログイン", login_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with url: login_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%=  f.password_field :password, class: 'form-control' %> 
        </div>
        <div class="actions">
          <%= f.submit (t 'defaults.login'), class: 'btn btn-primary' %>
        </div>
      <% end %>
      <div class='text-center'>
        <%= link_to (t '.to_register_page'), new_user_path %>
        <%= link_to (t '.password_forget'), "#" %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t ('.title') %></h1>
      <%= form_with model: @user, local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control'%> 
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit (t 'defaults.register'), class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <%= link_to (t '.to_login_page'), login_path %>
      </div>
    </div>
  </div>
</div>